spring:
  application:
    name: order-service
  cloud:
    nacos:
      server-addr: 43.138.208.107:8846
      discovery:
        username: nacos
        password: nacos
        namespace: public
server:
  port: 8081