spring:
  application:
    name: stock-service
  cloud:
    nacos:
      discovery:
        # /nacos 必不可少
        server-addr: 43.138.208.107:8846
        namespace: public
        username: nacos
        password: nacos
        service: ${spring.application.name}
server:
  port: 9091